openapi: 3.0.0
info:
  title: API Loja Virtual
  version: 0.1
servers:
  - url: http://localhost:3000/api-docs
tags:
  - name: produtos
paths:
  /produtos:
    post:
      tags:
        - produtos
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        201:
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        422:
          description: Dados do produto inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get:
      tags:
        - produtos
      responses:
        200:
          description: Lista de produtos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProdutos'


                
  /produtos/{id}:
    get:
      tags:
        - produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
        - produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        200:
          description: Produto atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Produto deletado com sucesso
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  schemas:
    Produto:
      type: object
      properties:
        nome:
          type: string
        preco:
          type: number
    ArrayOfProdutos:
      type: array
      items:
        $ref: '#/components/schemas/Produto'
    Mensagem:
      type: object
      properties:
        msg:
          type: string
